version: '3'
services:
  your_bot:
    build: .
    network_mode: host
    environment:
      - TELEGRAM_TOKEN=your_telegram_token
      - MAIN_ADMIN_ID=your_admin_id
    command: python3 installer.py --nointeract && python3 src/main.py
